lane :import_app_store do
  revenuecat_import_app_store_products(
    # apple_username: "you@example.com",
    # apple_team_name: "Your Team",
    # apple_app_identifier: "com.example.app"

    # revenuecat_api_key: "sk_xxxxxxxxxxxx",
    # revenuecat_project_id: "projXXXXXX",
    # revenuecat_app_id: "appXXXXX"
  )
end

lane :price_mapping_app_store do
  revenuecat_create_app_store_price_mapping(
    # apple_username: "you@example.com",
    # apple_team_name: "Your Team",
    # apple_app_identifier: "com.example.app"
  )
end